- Leia todas as bases com PySpark.
- Entenda o schema de cada uma.
- Verifique o volume de registros.
- Identifique as chaves de relacionamento.
- Faça uma exploração inicial dos dados.

### Passo 1: Importações

In [26]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Case").getOrCreate()

from pyspark.sql import functions as F
import pandas as pd

### Passo 2: Leitura das bases

In [6]:
PATH = '/home/tatiane/repositorios/data-projects/02_data_analysis/etl_banco_digital/bronze/'

agencias = spark.read.csv(f"{PATH}agencias.csv", header=True)
clientes = spark.read.csv(f"{PATH}clientes.csv", header=True)
pix = spark.read.csv(f"{PATH}pix.csv", header=True)
contas = spark.read.csv(f"{PATH}contas.csv", header=True)
transacoes = spark.read.csv(f"{PATH}transacoes_cartao.csv", header=True)

### Passo 3: Exploração inicial

- Volume de registros

In [12]:
bases = [agencias, clientes, pix, contas, transacoes]
nomes = ["agencias", "clientes", "pix", "contas", "transacoes de cartão"]
for nome, df in zip(nomes, bases):
    print('Schema da base de: ', nome)
    print('Qtd. registros:', df.count(), '| Quantidade de colunas: ', len(df.columns))
    df.printSchema()

Schema da base de:  agencias
Qtd. registros: 10 | Quantidade de colunas:  3
root
 |-- uf: string (nullable = true)
 |-- gerente_regional: string (nullable = true)
 |-- regiao: string (nullable = true)

Schema da base de:  clientes
Qtd. registros: 10020 | Quantidade de colunas:  7
root
 |-- id_cliente: string (nullable = true)
 |-- sexo: string (nullable = true)
 |-- uf: string (nullable = true)
 |-- renda: string (nullable = true)
 |-- cidade: string (nullable = true)
 |-- nome: string (nullable = true)
 |-- data_nascimento: string (nullable = true)

Schema da base de:  pix
Qtd. registros: 120000 | Quantidade de colunas:  5
root
 |-- id_pix: string (nullable = true)
 |-- id_conta: string (nullable = true)
 |-- valor: string (nullable = true)
 |-- status: string (nullable = true)
 |-- data_hora: string (nullable = true)

Schema da base de:  contas
Qtd. registros: 10000 | Quantidade de colunas:  5
root
 |-- id_conta: string (nullable = true)
 |-- id_cliente: string (nullable = true)
 |-- tipo_conta: string (nullable = true)
 |-- status: string (nullable = true)
 |-- data_abertura: string (nullable = true)

Schema da base de:  transacoes de cartão
Qtd. registros: 90000 | Quantidade de colunas:  5
root
 |-- id_compra: string (nullable = true)
 |-- id_conta: string (nullable = true)
 |-- categoria: string (nullable = true)
 |-- valor: string (nullable = true)
 |-- data_hora: string (nullable = true)

Chaves de relacionamento: 
Tabela de transações de cartão se comunica com as tabelas de contas e pix através da chave "id conta"
Tabela de agencias se comunica com a tabela de clientes através da chave "uf"
Tabela de clientes se comunica com a tabela de contas através da chave "id cliente"

agencias == cliente == contas == pix == transações.

- Conteúdo

In [15]:
for col in agencias.columns:
    agencias.groupBy(col).count().orderBy(col).show()

+---+-----+
| uf|count|
+---+-----+
| BA|    1|
| DF|    1|
| GO|    1|
| MG|    1|
| PE|    1|
| PR|    1|
| RJ|    1|
| RS|    1|
| SC|    1|
| SP|    1|
+---+-----+

+----------------+-----+
|gerente_regional|count|
+----------------+-----+
|          Bianca|    1|
|          Carlos|    1|
|           Diego|    1|
|        Fernanda|    1|
|            João|    1|
|           Lucas|    1|
|          Marina|    1|
|        Patrícia|    1|
|          Rafael|    1|
|          Renata|    1|
+----------------+-----+

+------------+-----+
|      regiao|count|
+------------+-----+
|Centro-Oeste|    2|
|    Nordeste|    2|
|     Sudeste|    3|
|         Sul|    3|
+------------+-----+

In [16]:
for col in clientes.columns:
    clientes.groupBy(col).count().orderBy(col).show()

+----------+-----+
|id_cliente|count|
+----------+-----+
|         1|    1|
|        10|    1|
|       100|    1|
|      1000|    1|
|     10000|    1|
|      1001|    1|
|      1002|    1|
|      1003|    1|
|      1004|    1|
|      1005|    1|
|      1006|    1|
|      1007|    1|
|      1008|    1|
|      1009|    1|
|       101|    1|
|      1010|    1|
|      1011|    1|
|      1012|    1|
|      1013|    1|
|      1014|    1|
+----------+-----+
only showing top 20 rows
+----+-----+
|sexo|count|
+----+-----+
|   F| 5023|
|   M| 4997|
+----+-----+

+---+-----+
| uf|count|
+---+-----+
| BA|  998|
| DF| 1058|
| GO|  977|
| MG|  993|
| PE| 1009|
| PR|  998|
| RJ|  977|
| RS|  979|
| SC| 1018|
| SP| 1013|
+---+-----+

+-------+-----+
|  renda|count|
+-------+-----+
|   NULL|   81|
|10003.0|    2|
|10006.0|    2|
|10012.0|    1|
|10016.0|    1|
|10019.0|    1|
|10020.0|    1|
|10023.0|    1|
|10026.0|    1|
|10027.0|    2|
|10034.0|    1|
|10035.0|    1|
|10036.0|    1|
|10040.0|    1|
|10047.0|    1|
|10050.0|    1|
|10051.0|    1|
|10053.0|    1|
|10054.0|    1|
|10056.0|    1|
+-------+-----+
only showing top 20 rows
+----------------+-----+
|          cidade|count|
+----------------+-----+
|        Anápolis|  334|
|  Belo Horizonte|  316|
|        Blumenau|  327|
|        Brasília| 1058|
|        Campinas|  342|
|          Campos|  346|
|         Caruaru|  303|
|   Caxias do Sul|  302|
|        Curitiba|  357|
|Feira de Santana|  322|
|   Florianópolis|  351|
|         Goiânia|  316|
|       Joinville|  340|
|    Juiz de Fora|  343|
|        Londrina|  299|
|         Maringá|  342|
|         Niterói|  316|
|         Pelotas|  345|
|       Petrolina|  343|
|    Porto Alegre|  332|
+----------------+-----+
only showing top 20 rows
+-------------+-----+
|         nome|count|
+-------------+-----+
|Cliente_00001|    1|
|Cliente_00002|    1|
|Cliente_00003|    1|
|Cliente_00004|    1|
|Cliente_00005|    1|
|Cliente_00006|    1|
|Cliente_00007|    1|
|Cliente_00008|    1|
|Cliente_00009|    1|
|Cliente_00010|    1|
|Cliente_00011|    1|
|Cliente_00012|    1|
|Cliente_00013|    1|
|Cliente_00014|    1|
|Cliente_00015|    1|
|Cliente_00016|    1|
|Cliente_00017|    1|
|Cliente_00018|    1|
|Cliente_00019|    1|
|Cliente_00020|    1|
+-------------+-----+
only showing top 20 rows
+-------------------+-----+
|    data_nascimento|count|
+-------------------+-----+
|1955-01-02 00:28:26|    1|
|1955-01-04 08:31:46|    1|
|1955-01-04 13:00:43|    1|
|1955-01-06 11:30:59|    1|
|1955-01-07 05:17:40|    1|
|1955-01-07 07:28:07|    1|
|1955-01-07 20:12:25|    1|
|1955-01-08 05:54:12|    1|
|1955-01-08 07:38:58|    1|
|1955-01-12 23:22:56|    1|
|1955-01-13 04:38:38|    1|
|1955-01-13 07:54:32|    1|
|1955-01-18 02:50:56|    1|
|1955-01-18 22:57:41|    1|
|1955-01-19 11:32:24|    1|
|1955-01-20 20:50:55|    1|
|1955-01-20 21:55:21|    1|
|1955-01-21 06:05:53|    1|
|1955-01-22 08:41:52|    1|
|1955-01-23 07:00:49|    1|
+-------------------+-----+
only showing top 20 rows

In [17]:
for col in pix.columns:
    pix.groupBy(col).count().orderBy(col).show()

+------+-----+
|id_pix|count|
+------+-----+
|     1|    1|
|    10|    1|
|   100|    1|
|  1000|    1|
| 10000|    1|
|100000|    1|
|100001|    1|
|100002|    1|
|100003|    1|
|100004|    1|
|100005|    1|
|100006|    1|
|100007|    1|
|100008|    1|
|100009|    1|
| 10001|    1|
|100010|    1|
|100011|    1|
|100012|    1|
|100013|    1|
+------+-----+
only showing top 20 rows

+--------+-----+
|id_conta|count|
+--------+-----+
|  100001|   12|
|  100002|    9|
|  100003|    4|
|  100004|   13|
|  100005|    9|
|  100006|   10|
|  100007|   12|
|  100008|   11|
|  100009|    5|
|  100010|   11|
|  100011|   14|
|  100012|   14|
|  100013|   10|
|  100014|   15|
|  100015|   15|
|  100016|    9|
|  100017|   16|
|  100018|   12|
|  100019|    8|
|  100020|   13|
+--------+-----+
only showing top 20 rows

+-----+-----+
|valor|count|
+-----+-----+
| NULL|  100|
|  0.0|    3|
| 0.01|    1|
| 0.02|    1|
| 0.03|    2|
| 0.04|    1|
| 0.07|    2|
| 0.08|    3|
| 0.09|    1|
|  0.1|    2|
| 0.11|    1|
| 0.12|    2|
| 0.14|    2|
| 0.15|    1|
| 0.16|    3|
| 0.17|    2|
| 0.18|    4|
| 0.19|    6|
|  0.2|    2|
| 0.21|    1|
+-----+-----+
only showing top 20 rows
+---------+------+
|   status| count|
+---------+------+
|Cancelado|  5978|
|Concluido|111641|
|   Falhou|  2381|
+---------+------+

[Stage 112:============================>                            (1 + 1) / 2]

+-------------------+-----+
|          data_hora|count|
+-------------------+-----+
|2026-01-01 00:02:09|    1|
|2026-01-01 00:03:10|    1|
|2026-01-01 00:04:20|    1|
|2026-01-01 00:06:28|    1|
|2026-01-01 00:11:45|    1|
|2026-01-01 00:15:42|    1|
|2026-01-01 00:15:45|    1|
|2026-01-01 00:15:52|    1|
|2026-01-01 00:19:33|    1|
|2026-01-01 00:23:53|    1|
|2026-01-01 00:28:57|    1|
|2026-01-01 00:33:09|    1|
|2026-01-01 00:35:15|    1|
|2026-01-01 00:35:52|    1|
|2026-01-01 00:36:03|    1|
|2026-01-01 00:37:08|    1|
|2026-01-01 00:38:28|    1|
|2026-01-01 00:40:29|    1|
|2026-01-01 00:41:24|    1|
|2026-01-01 00:43:48|    1|
+-------------------+-----+
only showing top 20 rows

In [18]:
for col in contas.columns:
    contas.groupBy(col).count().orderBy(col).show()

+--------+-----+
|id_conta|count|
+--------+-----+
|  100001|    1|
|  100002|    1|
|  100003|    1|
|  100004|    1|
|  100005|    1|
|  100006|    1|
|  100007|    1|
|  100008|    1|
|  100009|    1|
|  100010|    1|
|  100011|    1|
|  100012|    1|
|  100013|    1|
|  100014|    1|
|  100015|    1|
|  100016|    1|
|  100017|    1|
|  100018|    1|
|  100019|    1|
|  100020|    1|
+--------+-----+
only showing top 20 rows
+----------+-----+
|id_cliente|count|
+----------+-----+
|         1|    1|
|        10|    1|
|       100|    1|
|      1000|    1|
|     10000|    1|
|      1001|    1|
|      1002|    1|
|      1003|    1|
|      1004|    1|
|      1005|    1|
|      1006|    1|
|      1007|    1|
|      1008|    1|
|      1009|    1|
|       101|    1|
|      1010|    1|
|      1011|    1|
|      1012|    1|
|      1013|    1|
|      1014|    1|
+----------+-----+
only showing top 20 rows
+----------+-----+
|tipo_conta|count|
+----------+-----+
|  Corrente| 6958|
|   Digital| 3042|
+----------+-----+

+---------+-----+
|   status|count|
+---------+-----+
|    Ativa| 9208|
|Bloqueada|  509|
|Encerrada|  283|
+---------+-----+

+-------------------+-----+
|      data_abertura|count|
+-------------------+-----+
|2018-01-01 11:45:32|    1|
|2018-01-01 14:10:27|    1|
|2018-01-01 23:36:59|    1|
|2018-01-02 04:36:04|    1|
|2018-01-02 21:19:06|    1|
|2018-01-03 08:43:10|    1|
|2018-01-03 23:40:57|    1|
|2018-01-04 06:41:58|    1|
|2018-01-04 11:47:11|    1|
|2018-01-04 13:39:33|    1|
|2018-01-04 19:02:35|    1|
|2018-01-04 22:37:49|    1|
|2018-01-05 05:36:29|    1|
|2018-01-05 20:21:15|    1|
|2018-01-06 09:10:41|    1|
|2018-01-06 11:44:17|    1|
|2018-01-06 22:23:06|    1|
|2018-01-06 22:26:28|    1|
|2018-01-07 01:26:08|    1|
|2018-01-08 06:11:29|    1|
+-------------------+-----+
only showing top 20 rows

In [19]:
for col in transacoes.columns:
    transacoes.groupBy(col).count().orderBy(col).show()

+---------+-----+
|id_compra|count|
+---------+-----+
|        1|    1|
|       10|    1|
|      100|    1|
|     1000|    1|
|    10000|    1|
|    10001|    1|
|    10002|    1|
|    10003|    1|
|    10004|    1|
|    10005|    1|
|    10006|    1|
|    10007|    1|
|    10008|    1|
|    10009|    1|
|     1001|    1|
|    10010|    1|
|    10011|    1|
|    10012|    1|
|    10013|    1|
|    10014|    1|
+---------+-----+
only showing top 20 rows
+--------+-----+
|id_conta|count|
+--------+-----+
|  100001|   10|
|  100002|   10|
|  100003|    6|
|  100004|    6|
|  100005|    8|
|  100006|    6|
|  100007|    8|
|  100008|   16|
|  100009|    7|
|  100010|    8|
|  100011|    9|
|  100012|   10|
|  100013|   12|
|  100014|   10|
|  100015|    6|
|  100016|    7|
|  100017|    7|
|  100018|    7|
|  100019|    5|
|  100020|   13|
+--------+-----+
only showing top 20 rows
+-----------+-----+
|  categoria|count|
+-----------+-----+
|Combustivel|12849|
|   Farmacia|12928|
|    Mercado|12942|
|     Outros|12637|
|Restaurante|13008|
|  Streaming|12935|
|     Viagem|12701|
+-----------+-----+

+-----+-----+
|valor|count|
+-----+-----+
| 0.32|    1|
| 0.56|    1|
|  0.8|    1|
| 0.86|    1|
| 0.92|    1|
| 1.18|    1|
| 1.24|    1|
| 1.33|    1|
| 1.34|    1|
| 1.46|    1|
| 1.54|    1|
| 1.66|    1|
| 1.99|    1|
|10.03|    1|
|10.05|    1|
|10.08|    1|
| 10.1|    1|
|10.11|    1|
|10.13|    3|
| 10.2|    2|
+-----+-----+
only showing top 20 rows

[Stage 142:============================>                            (1 + 1) / 2]

+-------------------+-----+
|          data_hora|count|
+-------------------+-----+
|2026-01-01 00:02:45|    1|
|2026-01-01 00:07:00|    1|
|2026-01-01 00:07:53|    1|
|2026-01-01 00:08:25|    1|
|2026-01-01 00:13:09|    1|
|2026-01-01 00:17:36|    1|
|2026-01-01 00:25:09|    1|
|2026-01-01 00:25:22|    1|
|2026-01-01 00:34:15|    1|
|2026-01-01 00:36:31|    1|
|2026-01-01 00:36:57|    1|
|2026-01-01 00:46:21|    1|
|2026-01-01 00:54:23|    1|
|2026-01-01 01:03:43|    1|
|2026-01-01 01:10:13|    1|
|2026-01-01 01:17:35|    1|
|2026-01-01 01:22:20|    1|
|2026-01-01 01:23:28|    1|
|2026-01-01 01:23:52|    1|
|2026-01-01 01:28:05|    1|
+-------------------+-----+
only showing top 20 rows

- Resumo completo por base

In [28]:
bases = [agencias, clientes, pix, contas, transacoes]
nomes = ["agencias", "clientes", "pix", "contas", "transacoes de cartão"]
for nome, df in zip(nomes, bases):
    print('Resumo:', nome)
    colunas = df.columns
    resumo = []

    for col in colunas:
        total = df.count()
        nulos = df.filter(F.col(col).isNull()).count()
        duplicados = total - df.select(col).distinct().count()
        unicos = df.select(col).distinct().count()

        resumo.append({
            "coluna": col,
            "total": total,
            "duplicados": duplicados,
            "nulos": nulos,
            "valores_unicos": unicos
        })

    resumo_pd = pd.DataFrame(resumo)
    resumo_pd = resumo_pd.sort_values("duplicados", ascending=False).reset_index(drop=True)
    
    display(resumo_pd)

Resumo: agencias

             coluna  total  duplicados  nulos  valores_unicos
0            regiao     10           6      0               4
1                uf     10           0      0              10
2  gerente_regional     10           0      0              10

Resumo: clientes

            coluna  total  duplicados  nulos  valores_unicos
0             sexo  10020       10018      0               2
1               uf  10020       10010      0              10
2           cidade  10020        9992      0              28
3            renda  10020        1934     81            8086
4       id_cliente  10020          20      0           10000
5             nome  10020          20      0           10000
6  data_nascimento  10020          20      0           10000

Resumo: pix

      coluna   total  duplicados  nulos  valores_unicos
0     status  120000      119997      0               3
1   id_conta  120000      110000      0           10000
2      valor  120000       36901    100           83099
3  data_hora  120000         404      0          119596
4     id_pix  120000           0      0          120000

Resumo: contas

          coluna  total  duplicados  nulos  valores_unicos
0     tipo_conta  10000        9998      0               2
1         status  10000        9997      0               3
2       id_conta  10000           0      0           10000
3     id_cliente  10000           0      0           10000
4  data_abertura  10000           0      0           10000

Resumo: transacoes de cartão

      coluna  total  duplicados  nulos  valores_unicos
0  categoria  90000       89993      0               7
1   id_conta  90000       80001      0            9999
2      valor  90000       46303      0           43697
3  data_hora  90000         223      0           89777
4  id_compra  90000           0      0           90000

Existem nulos na coluna de renda da base de clientes;
Existem nulos na coluna de valor da base de pix;